### ISSUE TITLE
Error: Library "ctypes" in /usr/local/lib/ocaml/site-lib/ctypes is hidden

### ISSUE THREAD

**Issue by yurivict** [aantron/luv#125] opened 2021-08-31 17:09 UTC
I have ocaml-ctypes-0.19.1 installed but ocaml-luv-0.5.10 breaks:
```
File "_build/.dune/default/src/c/dune", line 9, characters 12-18:
9 |  (libraries ctypes luv_c_function_descriptions threads)
                ^^^^^^
Error: Library "ctypes" in /usr/local/lib/ocaml/site-lib/ctypes is hidden
(unsatisfied 'exist_if').
Hint: try:
  dune external-lib-deps --missing --no-config --root . --ignore-promoted-rules --default-target @install --always-show-command-line --promote-install-files --release --only-packages luv -p 
```

**Comment by aantron** [comment] 2021-09-22 12:39
I was unable to reproduce this with opam. I did:

```
opam update
opam install ctypes.0.19.1
opam install luv.0.5.10
```

...and all worked well. `opam list` confirms that the right versions got installed.

From the package names, it looks like you are not working with opam, but with a system package manager. From the error message, this looks most likely like an issue with Ctypes packaging rather than with Luv. I see that you have already opened https://github.com/ocamllabs/ocaml-ctypes/issues/687 at Ctypes about this. I suggest commenting in that issue on what commands can be executed to reproduce the error message, otherwise it will likely be difficult for an opam user to observe and debug it (as it is for me, since it works for me with opam).

I am closing the issue in this repo in favor of https://github.com/ocamllabs/ocaml-ctypes/issues/687, but we can continue here if debugging in https://github.com/ocamllabs/ocaml-ctypes/issues/687 suggests that this is actually a Luv issue.

**Closed by aantron** 2021-09-22 12:39 UTC
