### ISSUE TITLE
luv 0.5.9 fails to build from opam on windows 32

### ISSUE THREAD

**Issue by RealyUniqueName** [aantron/luv#121] opened 2021-07-27 08:34 UTC
```
#=== ERROR while compiling luv.0.5.9 ==========================================#
# context              2.0.8 | win32/x86_64 | ocaml-variants.4.07.0+mingw32c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path                 ~/.opam/4.07.0+mingw32c/.opam-switch/build/luv.0.5.9
# command              C:\cygwin\home\runneradmin\.opam\4.07.0+mingw32c\bin\dune.exe build -p luv -j 1
# exit-code            1
# env-file             ~/.opam/log/luv-4536-ae662f.env
# output-file          ~/.opam/log/luv-4536-ae662f.out
### output ###
# i686-w64-mingw32-gcc src/c/helpers.o
# helpers.c: In function ‘luv_is_invalid_handle_value’:
# helpers.c:656:16: warning: comparison between pointer and integer
#   656 |     if (handle == -1)
#       |                ^~
#         bash src/c/dlluv.dll,src/c/libuv.a (exit 2)
# (cd _build/default/src/c/vendor/libuv && C:\cygwin\bin\bash.exe -e -u -o pipefail -c "$([ 'Win32' = Unix ] && echo C:\cygwin\bin\make.exe || echo make) V=0 -j 4 -o aclocal.m4 -o Makefile.in -o configure -o configure.status -o Makefile libuv.la" &> C:\cygwin\home\runneradmin\.opam\4.07.0+mingw32c\.opam-switch\build\luv.0.5.9\nul
```
https://github.com/HaxeFoundation/haxe/runs/3159888709#step:9:454

**Comment by aantron** [comment] 2021-07-27 09:50
Can you show the full log? In this build, [it was](https://github.com/HaxeFoundation/haxe/runs/3159888709#step:9:460) `~/.opam/log/luv-4536-ae662f.out`. It should be enough to add a `cat ~/.opam/log/luv*.out` command to the CI in a branch.

**Comment by RealyUniqueName** [comment] 2021-07-27 12:01
https://github.com/HaxeFoundation/haxe/runs/3170729851#step:9:531

**Comment by aantron** [comment] 2021-07-27 14:19
Thanks.

Even though it's the only message in the log, I am skeptical that it is the cause of the build failure, for several reasons, including:

- It is only a warning (though it would be good to fix it), and `-Werror` is not enabled.
- The code it points to was [already present](https://github.com/aantron/luv/commit/decdaad7511855d012e31f22b35538ddd874c08d#diff-1d3c256345b03e6c09f8b5c61838868d99c406f05e7441b616f0f5a2a51ac71dR654) in 0.5.8, and I understand that 0.5.8 is working for you.
- Now that I checked the Windows logs for this repo's own CI, it looks like the warning [appears](https://github.com/aantron/luv/runs/3122949081#step:6:11) there as well, yet the build does not fail.

Could you add more verbosity options to the debug branch?

- [Here](https://github.com/HaxeFoundation/haxe/commit/d447e0be2716081feb95c3d94c37be9a56ecb3b5#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R205) add `--verbose`.
- If you can pin to a variant of 0.5.9, can you clone Luv and change its opam file to [pass](https://github.com/aantron/luv/blob/master/luv.opam#L27) `--verbose` to `dune build`?
- [Here](https://github.com/aantron/luv/blob/ac7367839175533bd867c2749ae7de07e1e4fba0/src/c/dune#L77-L80), unwrap the `(ignore-outputs ...)` and replace `V=0` by `V=1` (note: I should add that to a new CONTRIBUTING.md because I forgot how to do that myself).

https://github.com/aantron/luv/blob/ac7367839175533bd867c2749ae7de07e1e4fba0/src/c/dune#L77-L80

**Comment by aantron** [comment] 2021-08-03 11:01
@RealyUniqueName, the above commit (32001f81446af56204d626adc379e274d53c043b) makes the Luv and libuv builds verbose. Can you try building with this commit? It should help us to see what might actually cause the error... or so I hope.

**Comment by RealyUniqueName** [comment] 2021-08-05 08:38
Sorry for late response. Here's the log: https://github.com/HaxeFoundation/haxe/runs/3249965601#step:9:583

**Comment by aantron** [comment] 2021-08-05 10:15
Thanks.

[This line](https://github.com/HaxeFoundation/haxe/runs/3249965601#step:9:1156) appears the most likely to be relevant:

```
/home/runneradmin/.opam/4.07.0+mingw32c/.opam-switch/build/luv.0.5.9/_build/default/src/c/vendor/libuv/src/win/util.c:1677: undefined reference to `GetHostNameW'
```

So I'm continuing by looking into that.

**Comment by aantron** [comment] 2021-08-05 10:22
I see two issues in libuv, which suggest that this is an issue between recent libuv and MinGW:

- https://github.com/libuv/libuv/issues/3178
- https://github.com/libuv/libuv/issues/3260

I wonder why it didn't come up during #123. Can you spot the difference in the setups, given the information in the libuv issues?

**Comment by aantron** [comment] 2021-08-05 10:24
Ah, well #123 was targetting Fedora. Don't know why I remembered it as Windows :) So that would probably explain it.

**Comment by aantron** [comment] 2021-08-05 10:28
Ok, so, in summary, it looks like Luv should be held back to 0.5.8 until <https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2c0bc10db78341d28fe39deb645dcb55c05e52d7/> is released in MinGW and available for installation. AFAIK there is nothing (reasonable, short of making our own branch off libuv with a workaround) that can be done on the Luv side. In that case, I'll release 0.5.10 with the fix for #123, which should also be an issue for 32-bit Windows builds after the MinGW issue is fixed. Once the MinGW issue is fixed, you should be able to upgrade straight to 0.5.10.

**Comment by aantron** [comment] 2021-08-05 10:38
Alternatively, you could try building Luv against a separately-installed earlier version of libuv than 1.42.0, rather than the vendored 1.42.0, a usage which Luv does support, but I suspect that this will be more complicated than you'd like to deal with (I wouldn't want to!). There aren't any major bugfixes on the Luv side in 0.5.9, just #113. It's mainly just a libuv upgrade (to a temporarily broken version because of MinGW).

**Comment by RealyUniqueName** [comment] 2021-08-05 10:48
We're fine with 0.5.8.

Thanks for your work!

**Comment by aantron** [comment] 2021-08-05 14:01
Thanks for reporting and getting the logs!

I'll leave this issue open and maybe ping it in some months, hopefully MinGW will have been updated by then and this will be fully resolved.

**Comment by Simn** [comment] 2022-04-06 07:03
I've [just tried](https://github.com/HaxeFoundation/haxe/commit/16070474ebef2bd0297fb4b5c288c46746265b75) using latest luv and that worked fine. 0.5.7 was suddenly causing a different error which I didn't understand:

```
#=== ERROR while compiling luv.0.5.7 ==========================================#
# context              2.0.10 | win32/x86_64 | ocaml-variants.4.07.0+mingw64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path                 ~/.opam/4.07.0+mingw64c/.opam-switch/build/luv.0.5.7
# command              C:\cygwin64\home\runneradmin\.opam\4.07.0+mingw64c\bin\dune.exe build -p luv -j 1
# exit-code            1
# env-file             ~/.opam/log/luv-6608-813bac.env
# output-file          ~/.opam/log/luv-6608-813bac.out
### output ###
# File "_build/.dune/default/src/c/dune", line 41, characters 0-813:
# 41 | (rule
# 42 |  (targets libuv.a dlluv%{ext_dll})
# 43 |  (deps (source_tree vendor))
# ....58 |    "cp vendor/libuv/libuv.so.1.0.0 dlluv.so || \
# 59 |     cp vendor/libuv/libuv.1.dylib dlluv.so || \
# 60 |     cp vendor/bin/libuv-1.dll dlluv.dll")))))
# (cd _build/default/src/c/vendor/libuv && C:\cygwin64\bin\bash.exe -e -u -o pipefail -c "$([ 'Win32' = Unix ] && echo C:\cygwin64\bin\make.exe || echo make) V=0 -j 4 -o aclocal.m4 -o Makefile.in -o configure -o configure.status -o Makefile libuv.la" &> C:\cygwin64\home\runneradmin\.opam\4.07.0+mingw64c\.opam-switch\build\luv.0.5.7\nul
# Command exited with code 2.
```

I don't really know what changed to cause this, but oh well.

**Comment by aantron** [comment] 2022-04-06 07:31
Great, thank you! I am closing this issue, as it appears to be resolved.

**Closed by aantron** 2022-04-06 07:31 UTC
