### ISSUE TITLE
dune runtest fails with signal ABRT

### ISSUE THREAD

**Issue by olafhering** [aantron/luv#106] opened 2021-04-16 21:47 UTC
The testsuite of [ocaml-luv.rpm](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-luv) (currently 2ef633714fa8265d6b1b2a888c2302baa98c8fc4) fails with `ABRT`. It might be related to the lack of network within the build VM.

[Full log](https://build.opensuse.org/build/devel:languages:ocaml/openSUSE_Tumbleweed/x86_64/ocaml-luv:testsuite/_log)

````
[   49s] Running[311]: (cd _build/default/test && ./tester.exe)
[   52s] Command [311] got signal ABRT:
[   52s] $ (cd _build/default/test && ./tester.exe)
[   52s] Testing `luv'.
...
[   52s]   [OK]          tcp                 14   read, write.
[   52s]   [OK]          tcp                 15   eof.
[   52s] + echo 'dune runtest failed'
````

**Comment by aantron** [comment] 2021-04-18 08:12
@olafhering I don't recognize the error and I'm not certain how I could reproduce it &mdash; could you offer any more detailed information about the environment in the VM, or a way to debug inside it?

I am not able to access the full log. I get "anonymous_user(Anonymous user is not allowed here - please login):"

**Comment by aantron** [comment] 2021-04-18 08:19
It looks like I was able to access the log through a [link](https://build.opensuse.org/package/live_build_log/devel:languages:ocaml/ocaml-luv:testsuite/openSUSE_Tumbleweed/x86_64) on the package page. The other obstacles still stand!

The test that is most likely to be triggering this is:

https://github.com/aantron/luv/blob/2ef633714fa8265d6b1b2a888c2302baa98c8fc4/test/TCP.ml#L293-L305

That is the next test after the last one to succeed, `"eof"`.

What this test does is create a TCP handle, leave it unconnected, and then try to write zero bytes to it, expecting either `EBADF` or `EPIPE`.

**Comment by olafhering** [comment] 2021-04-19 09:40
I suspect my `ocaml-ctypes` package is broken. The tester just crashes in my Leap 15.1 environment, have not tried Tumbleweed..

````
/usr/bin/time /usr/bin/env -i PATH=/usr/bin:/bin LUV_USE_SYSTEM_LIBUV=yes /usr/bin/strace -f -s 1234 -tt -o /dev/shm/$$ /usr/bin/dune runtest --verbose --for-release-of-packages=luv -j1
...
Apr 19 11:13:34 systemd-coredump[14509]: Process 14500 (tester.exe) of user 1000 dumped core.

Stack trace of thread 14500:
#0  0x00007fcec6ebe520 __GI_raise (libc.so.6)
#1  0x00007fcec6ebfb01 __GI_abort (libc.so.6)
#2  0x00007fcec6eb6b1a __assert_fail_base (libc.so.6)
#3  0x00007fcec6eb6b92 __GI___assert_fail (libc.so.6)
#4  0x00007fcec79b4941 uv_write2 (libuv.so.1)
#5  0x00000000005cca74 luv_stub_79_uv_write2 (tester.exe)
#6  0x00000000004f5175 camlLuv_c_generated_functions__fun_6184 (tester.exe)
#7  0x00000000004e6e98 camlLuv__Stream__write_general_4221 (tester.exe)
#8  0x00000000004c6042 camlDune__exe__TCP__fun_4410 (tester.exe)
#9  0x00000000004c47a5 camlDune__exe__TCP__with_tcp_inner_4068 (tester.exe)
#10 0x0000000000539fb8 camlAlcotest_engine__Core__fun_4094 (tester.exe)
#11 0x0000000000534b79 camlAlcotest_engine__Monad__catch_169 (tester.exe)
#12 0x000000000053b187 camlAlcotest_engine__Core__fun_3503 (tester.exe)
#13 0x000000000052d2be camlAlcotest__fun_2278 (tester.exe)
#14 0x000000000053a51c camlAlcotest_engine__Core__fun_5060 (tester.exe)
#15 0x0000000000534e06 camlAlcotest_engine__Monad__inner_193 (tester.exe)
#16 0x000000000053c369 camlAlcotest_engine__Core__fun_4746 (tester.exe)
#17 0x000000000053bd40 camlAlcotest_engine__Core__run_with_args_2534 (tester.exe)
#18 0x0000000000568dc8 camlCmdliner_term__fun_182 (tester.exe)
#19 0x000000000056bd27 camlCmdliner__run_414 (tester.exe)
#20 0x000000000056c038 camlCmdliner__term_eval_440 (tester.exe)
#21 0x000000000056cc2b camlCmdliner__eval_choice_inner_1638 (tester.exe)
#22 0x0000000000541285 camlAlcotest_engine__Cli__run_with_args_inner_2649 (tester.exe)
#23 0x00000000004beb18 camlDune__exe__Tester__entry (tester.exe)
#24 0x00000000004b9539 caml_program (tester.exe)
#25 0x00000000005febd4 caml_start_program (tester.exe)
#26 0x00000000005de88c caml_startup_common (tester.exe)
#27 0x00000000005de8cb caml_startup_exn (tester.exe)
#28 0x00000000004b88fc main (tester.exe)
#29 0x00007fcec6ea934a __libc_start_main (libc.so.6)
#30 0x00000000004b893a _start (tester.exe)

Stack trace of thread 14502:
#0  0x00007fcec6f78553 __GI___select (libc.so.6)
#1  0x00000000005d21e1 caml_thread_tick (tester.exe)
#2  0x00007fcec77844f9 start_thread (libpthread.so.0)
#3  0x00007fcec6f80fbf __clone (libc.so.6)
....
14500 11:13:34.803571 write(2, "tester.exe: src/unix/stream.c:1405: uv_write2: Assertion `nbufs > 0' failed.\n", 77) = 77
````

running tester.exe with gdb, setting a breakpoint at `luv_stub_79_uv_write2` reveals, `nbufs` is indeed zero in the second invocation of the breakpoint.

**Comment by olafhering** [comment] 2021-04-19 10:56
I tried a non-dune build of `ocaml-ctypes 0.18`, but that does not fix the testsuite of `luv`.

**Comment by aantron** [comment] 2021-04-19 11:08
@olafhering, the assertion failure makes sense, because if you look at the test case, you will see that it is using `[]` for the buffer list. Try building with branch [`nbufs`](https://github.com/aantron/luv/commit/4b49d3edad2179c76d685500edf1b44f61ec4be8), where I added a proposed fix for this.

**Comment by aantron** [comment] 2021-04-19 11:10
Is there something special about this build or libuv in it, that it is triggering the assertion, like debug mode enabled? Because it was not triggered by other builds, or observed before, yet AFAICT the assertion is not conditional on the system or other such condition:

https://github.com/libuv/libuv/blob/47e0c5c575e92a25e0da10fc25b2732942c929f3/src/unix/stream.c#L1393-L1401

**Comment by olafhering** [comment] 2021-04-19 11:49
I'm not familier with [libuv](https://build.opensuse.org/package/show/openSUSE:Factory/libuv). The `assert` is indeed unconditional, hopefully no-one builds with `-DNDEBUG`. 

With the `nbufs` branch the tests gets further, but hangs apparently forever in `close_reset.`.

I should probably open another issue for that.

**Closed** 2021-04-20 14:38 UTC
